version: "3.9"
services:
  plex_prerolls:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./on_host/config:/config
      - ./on_host/logs:/logs
      - ./on_host/prerolls:/files
      - ./on_host/renders:/renders
      - ./on_host/auto_rolls:/auto_rolls
    ports:
      - "8283:8283"
    environment:
      TZ: America/New_York
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8283/last-run-within?timeframe=24h"]  # Adjust the timeframe as needed
      interval: 5m
      timeout: 10s
      retries: 3
